name: Nightly TypeScript Run

# run the typescript@next Ember Try job...
jobs:
  ts-next:
    name: typescript@next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --non-interactive
      - run: './node_modules/.bin/ember try:one ts-next'

# ...nightly at midnight
on:
  schedule:
    - cron: 0 0 * * *
